services:
  mysql:
    image: mysql:8.0
    container_name: mysql-meeting
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meetingBooking

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka-meeting
    ports:
      - "9092:9092"

volumes:
  mysql_data: